version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          PGHOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/postgres:11.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler:2.1.2
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Database creation
          command: bundle exec rake db:create db:schema:load --trace
      - run:
          name: Database migration
          command: bundle exec rake db:migrate
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Run tests
          command: bundle exec rspec
