version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
      - image: circleci/postgres:11.5
    steps:
      - checkout
      - run: 
          name: Install Bundler
          command: gem install bundler:2.1.2
      - run: 
          name: Install dependencies
          command: bundle install
      - run:
          name: Run rubocop
          command: bundle exec rubocop
      - run:
          name: Run tests
          command: bundle exec rspec
